-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; 
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;

SELECT * FROM TableName WITH (NOLOCK);

COMMIT TRANSACTION;

