mojagrupa:
  hosts:
    docker1:
      ansible_host: 172.17.0.2
      ansible_user: root
    docker2:
      ansible_host: 172.17.0.3
      ansible_user: root
    docker3:
      ansible_host: 172.17.0.4
      ansible_user: root
grupa2:
  hosts:
    docker1:
    docker3:
