export const initialRows = [
    {
        id: 1,
        name: "Name1",
        type: "Type1",
        price: 100,
        accessibility: true,
        pcs: 10,
    },
    {
        id: 2,
        name: "Name2",
        type: "Type2",
        price: 200,
        accessibility: false,
        pcs: 20,
    },
    {
        id: 3,
        name: "Name3",
        type: "Type3",
        price: 300,
        accessibility: true,
        pcs: 30,
    },
    {
        id: 4,
        name: "Name4",
        type: "Type4",
        price: 400,
        accessibility: false,
        pcs: 40,
    },
    {
        id: 5,
        name: "Name5",
        type: "Type5",
        price: 500,
        accessibility: true,
        pcs: 50,
    },
    {
        id: 6,
        name: "Name6",
        type: "Type6",
        price: 600,
        accessibility: true,
        pcs: 60,
    },
    {
        id: 7,
        name: "Name7",
        type: "Type7",
        price: 700,
        accessibility: false,
        pcs: 70,
    },
    {
        id: 8,
        name: "Name8",
        type: "Type8",
        price: 800,
        accessibility: true,
        pcs: 80,
    },
    {
        id: 9,
        name: "Name9",
        type: "Type9",
        price: 900,
        accessibility: false,
        pcs: 90,
    },
    {
        id: 10,
        name: "Name10",
        type: "Type10",
        price: 1000,
        accessibility: true,
        pcs: 100,
    },
    {
        id: 11,
        name: "Name11",
        type: "Type11",
        price: 1100,
        accessibility: true,
        pcs: 110,
    },
    {
        id: 12,
        name: "Name12",
        type: "Type12",
        price: 1200,
        accessibility: false,
        pcs: 120,
    },
    {
        id: 13,
        name: "Name13",
        type: "Type13",
        price: 1300,
        accessibility: true,
        pcs: 130,
    },
    {
        id: 14,
        name: "Name14",
        type: "Type14",
        price: 1400,
        accessibility: false,
        pcs: 140,
    },
    {
        id: 15,
        name: "Name15",
        type: "Type15",
        price: 1500,
        accessibility: true,
        pcs: 150,
    },
];